<?php
namespace psyml\admin;
use \psyml\core\Hexaco as Hexaco;
use \psyml\admin\Content as Content;

//spin it
\psyml\admin\Pages::run();

class Pages extends \psyML_Wp{


    public static function run(){

        \add_action( 'init', array( get_class(), 'add_psyml' ), 1  );
        \add_action( 'init', array( get_class(), 'add_psyml_subdimensions' ), 1  );
        \add_action( 'init', array( get_class(), 'add_psyml_pages' ),2 );
        \add_action( 'init', array( get_class(), 'add_psyml_subdimension_pages' ),2 );
        \add_action( 'admin_menu', array( get_class(), 'add_psyml_page_menu'));
        \add_action( 'admin_menu', array(get_class(), 'add_psyml_subdimensions_menu'));
        \add_filter('pre_get_posts', array( get_class(), 'psyml_pages_admin_order') );

        #add archive pages
        \add_filter( 'template_include', array( get_class(), 'psyml_archive_template' ));

        #add gatekeeper code to prevent changing page slugs of our dynamic pages
        \add_action('pre_post_update', array( get_class(), 'slug_defender'), 10,2 );
        \add_action('admin_init', array( get_class(), 'slug_defender_message_check'));

    }

    public static function slug_defender_message(){
        ?>
        <div class="notice notice-error is-dismissible">
            <p>The page you are editing has been auto-generated by the <?php echo self::nice_name ?> plugin. Permalink edits are not allowed.</p>
        </div>
        <?php
    }
    public static function slug_defender_message_check(){
        if(isset($_GET['psyml_notice']) && $_GET['psyml_notice'] == 1){
            \add_action('admin_notices', array( get_class(), 'slug_defender_message'));
        }
    }

    public static function slug_defender( $post_id, $data){
        if($data['post_type'] == 'psyml' || $data['post_type'] == 'psyml-subdimension'){
            $oldslug = \get_post_field( 'post_name', $post_id );
            if(isset($data['post_name']) && $data['post_name'] !== $oldslug ){

                //Sorry sir, your kind isn't welcome here
                #since we're dying, there's no way to hook admin notices so we carry in the URL string
                #Functionality disabled until we can find a better way around it
               # \wp_safe_redirect( \get_admin_url() . 'post.php?post='.$post_id.'&action=edit&psyml_notice=1');
               # die();


            }
            
        }
    }

    public static function delete_all_pysml_posts(){
        $args = array(
            'post_type' => 'psyml',
            'posts_per_page' => -1
        );

        $query = new \WP_Query($args);
        if ($query->have_posts() ) {
            while( $query->have_posts() ) {
                $query->the_post();
                \wp_delete_post( get_the_ID() );
            }
        }
        \wp_reset_postdata();
        $args = array(
            'post_type' => 'psyml-subdimension',
            'posts_per_page' => -1
        );

        $query = new \WP_Query($args);
        if ($query->have_posts() ) {
            while( $query->have_posts() ) {
                $query->the_post();
                \wp_delete_post( get_the_ID() );
            }
        }
        \wp_reset_postdata();
            
    }


    public static function psyml_archive_template( $template ){

        if(\is_page( 'psyml-results') ){
            // Set this to the template file inside your plugin folder
            $template = self::get_plugin_path() .'theme/templates/hexaco-landing.php';
        }
        return $template;
    }
    public static function add_psyml_subdimension_pages(){
        $auto_add = \get_option('auto_add_psyml');
        if($auto_add == "yes"){
            foreach( Content::SUBDIMENSION as $dimension => $subarray){

              $high = self::add_psyml_subdimension($dimension, 'high' );
              $medium = self::add_psyml_subdimension($dimension, 'medium' );
              $low = self::add_psyml_subdimension($dimension, 'low' );
            }
            #then add archive
            self::add_page('psyml-results', 'Your psyML Analysis Results');
            \update_option('auto_add_psyml', 'no');
        }
    }
    private static function get_psyml_page_content( $key ){

        $content = Hexaco::ARCHETYPES[$key]['content'];
        $roles = Hexaco::ARCHETYPES[$key]['roles'];
        $story = Hexaco::ARCHETYPES[$key]['story'];
 

        $roleslist = explode(',', $roles);
        $rolestemplate = '';
        foreach($roleslist as $list){
            $rolestemplate.='<li>'.$list.'</li>';
        }

        $template= '<div class="psymlcontent">'.$content.'</div>';
        $template.= '<h4>'. Hexaco::ARCHETYPES[$key]['name'].' excels in roles like:</h4>';
        $template.= '<ul class="psymlroles">'.$rolestemplate.'</ul>';
        $template.= '<h4>Sample Story:</h4>';
        $template.= '<div class="psymlstory">'.$story.'</div>';
        $template.= '</div>';
        return $template;
    }
    private static function add_featured_image_to_page( $key, $post_id, $imgtype = '.jpg' ){
         // Add Featured Image to Post
    $image_path        = self::get_plugin_path() . 'dist/assets/'.$key.$imgtype; // Define the image path
    $image_name        = 'psyml-'.$key.$imgtype;
    $upload_dir        = \wp_upload_dir(); // Set upload folder
    $image_data        = file_get_contents($image_path); // Get image data

    if($image_data){
        $unique_file_name = \wp_unique_filename( $upload_dir['path'], $image_name ); // Generate unique name
        $filename         = basename( $unique_file_name ); // Create image file name

            // Check folder permission and define file location
        if( \wp_mkdir_p( $upload_dir['path'] ) ) {
            $file = $upload_dir['path'] . '/' . $filename;
        } else {
            $file = $upload_dir['basedir'] . '/' . $filename;
        }
        // Create the image  file on the server
        file_put_contents( $file, $image_data );

        // Check image file type
        $wp_filetype = \wp_check_filetype( $filename, null );

        // Set attachment data
        $attachment = array(
            'post_mime_type' => $wp_filetype['type'],
            'post_title'     => \sanitize_file_name( $filename ),
            'post_content'   => '',
            'post_status'    => 'inherit'
        );

        // Create the attachment
        $attach_id = \wp_insert_attachment( $attachment, $file, $post_id );

        // Include image.php
        require_once(ABSPATH . 'wp-admin/includes/image.php');

        // Define attachment metadata
        $attach_data = \wp_generate_attachment_metadata( $attach_id, $file );

        // Assign metadata to attachment
        \wp_update_attachment_metadata( $attach_id, $attach_data );

        // And finally assign featured image to post
        \set_post_thumbnail( $post_id, $attach_id );

        }

    }

    public static function add_psyml_page_menu(){
        \add_submenu_page( 
            'psyml-settings',
            'psyML Pages', 
            'psyML Pages', 
            'administrator', 
            'edit.php?post_type=psyml',
        );
    }
    public static function add_psyml_subdimensions_menu(){
        \add_submenu_page(
            'psyml-settings',
            'psyML Subdimensions',
            'psyML Subdimensions',
            'administrator',
            'edit.php?post_type=psyml-subdimension',
        );
    }

    private static function add_page($slug, $title){
        $new_page_id = false;
        $content = '';
        $page_check = \get_page_by_path( $slug, OBJECT, 'page');
        $page = array(
            'post_type' => 'page',
            'post_title' => $title,
            'post_content' => $content,
            'post_status' => 'publish',
            'post_name' => $slug
        );
        if( !isset($page_check->ID)){
            $new_page_id = \wp_insert_post($page);
        }
    }
    private static function add_psyml_subdimension($dimension, $degree){
        $new_page_id = false;
        $title = ucwords(str_replace('_',' ',$degree)) . ' ' . ucfirst($dimension);
        $content =  '<div class="psymlcontent">' . Content::SUBDIMENSION[$dimension][$degree] . '</div>';
        $page_check = \get_page_by_path($dimension.'_'.$degree, OBJECT, 'psyml-subdimension');
        $page = array(
                'post_type' => 'psyml-subdimension',
                'post_title' => $title,
                'post_content' => $content,
                'post_status' => 'publish',
                'post_name' => $dimension.'_'.$degree
        );
        if( !isset($page_check->ID) ){
            $new_page_id = \wp_insert_post($page);
        }
        /*
        if($new_page_id) {

            #apparently this needs to be integer term id not slug
            $term = get_term_by('slug', strtolower($key), 'hexaco');

            $tagged = \wp_set_object_terms( $new_page_id, $term->term_id, 'hexaco', false);
            $featured_image = self::add_featured_image_to_page( $key, $new_page_id, '.jpg' );
        }
        */
        return $new_page_id;
          
    }

    private static function add_psyml_page($key){
        $new_page_id = false;
        $title = Hexaco::ARCHETYPES[$key]['name'];;
        $content = self::get_psyml_page_content( $key );
        $page_check = \get_page_by_path('psyml_'.$key, OBJECT, 'psyml');
        $page = array(
                'post_type' => 'psyml',
                'post_title' => $title,
                'post_content' => $content,
                'post_status' => 'publish',
                'post_name' => 'psyml_'.$key
        );
        if( !isset($page_check->ID) ){
            $new_page_id = \wp_insert_post($page);
        }
        if($new_page_id) {

            #apparently this needs to be integer term id not slug
            $term = get_term_by('slug', strtolower($key), 'hexaco');

            $tagged = \wp_set_object_terms( $new_page_id, $term->term_id, 'hexaco', false);
            $featured_image = self::add_featured_image_to_page( $key, $new_page_id, '.jpg' );
        }
          
    }

    public static function add_psyml_pages(){
        $auto_add = \get_option('auto_add_psyml');

        if($auto_add === "yes"){
            #start of process - delete the old pages first
            self::delete_all_pysml_posts();
            #then
            foreach( Hexaco::HEXACO as $idx => $array ){
                $key = $array['Key'];
                self::add_psyml_page($key);

                #then add archive
                self::add_page('psyml-results', 'Your psyML Analysis Results');
            }
        # we will do this on sub-dimension pages, which fire later
        #\update_option('auto_add_psyml', 'no');
        }

    }
    public static function psyml_pages_admin_order( $wp_query ) {
        if (\is_admin()) {
      
          // Get the post type from the query
          $post_type = $wp_query->query['post_type'];
      
          if ( $post_type == 'colorcontent') {
      
            $wp_query->set('orderby', 'title');
      
            $wp_query->set('order', 'ASC');
          }
        }
    }
    public static function add_psyml(){
        $psyml_labels = array(
            'name'               => _x( 'psyML', 'post type general name', self::text_domain ),
            'singular_name'      => _x( 'psyML Page', 'post type singular name', self::text_domain ),
            'menu_name'          => _x( 'psyML Pages', 'admin menu', self::text_domain ),
            'name_admin_bar'     => _x( 'psyML Page', 'add new on admin bar', self::text_domain ),
            'add_new'            => _x( 'New', 'psyML', self::text_domain ),
            'add_new_item'       => __( 'New psyML Page', self::text_domain ),
            'new_item'           => __( 'New psyML Page', self::text_domain ),
            'edit_item'          => __( 'Edit psyML Page', self::text_domain ),
            'view_item'          => __( 'View psyML Page', self::text_domain ),
            'all_items'          => __( 'psyML Pages', self::text_domain ),
            'search_items'       => __( 'Search psyML Content', self::text_domain ),
            'not_found'          => __( 'No psyML Page found.', self::text_domain ),
            'not_found_in_trash' => __( 'No psyML Page found in Trash.', self::text_domain )
        );
        
        $args = array(
            'labels'             => $psyml_labels,
            'description'        => __( 'Page content for psyML tagged content', self::text_domain ),
            'public'             => true,
            'publicly_queryable' => true,
            'show_ui'            => true,
            'show_in_menu'       => 'admin.php?page=psyml-settings',
            'query_var'          => true,
            'rewrite'            => array( 'slug' => 'psyml' ),
            'capability_type'    => 'post',
            'has_archive'        => true,
            'hierarchical'       => false,
            'menu_icon'          => 'dashicons-admin-post',
            'menu_position'      => 5,
            'show_in_rest'       => false,
          #  'rest_base'          => 'psyML',
          #  'rest_controller_class' => 'WP_REST_Posts_Controller',
            'supports'           => array( 'title', 'editor', 'thumbnail', 'page-attributes'),
            'taxonomies'         => array( 'hexaco')       
        );
    
        \register_post_type( 'psyml', $args );

    }
        public static function add_psyml_subdimensions(){
        $psyml_labels = array(
            'name'               => _x( 'psyML Subdimensions', 'post type general name', self::text_domain ),
            'singular_name'      => _x( 'psyML Subdimension', 'post type singular name', self::text_domain ),
            'menu_name'          => _x( 'psyML Subdimensions', 'admin menu', self::text_domain ),
            'name_admin_bar'     => _x( 'psyML Subdimension', 'add new on admin bar', self::text_domain ),
            'add_new'            => _x( 'New', 'psyML Subdimension', self::text_domain ),
            'add_new_item'       => __( 'New psyML Subdimension', self::text_domain ),
            'new_item'           => __( 'New psyML Subdimension', self::text_domain ),
            'edit_item'          => __( 'Edit psyML Subdimension', self::text_domain ),
            'view_item'          => __( 'View psyML Subdimension', self::text_domain ),
            'all_items'          => __( 'psyML Subdimensions', self::text_domain ),
            'search_items'       => __( 'Search psyML Subdimension Content', self::text_domain ),
            'not_found'          => __( 'No psyML Subdimension found.', self::text_domain ),
            'not_found_in_trash' => __( 'No psyML Subdimension found in Trash.', self::text_domain )
        );
        
        $args = array(
            'labels'             => $psyml_labels,
            'description'        => __( 'Subdimension content for psyML tagged content', self::text_domain ),
            'public'             => true,
            'publicly_queryable' => true,
            'show_ui'            => true,
            'show_in_menu'       => 'admin.php?page=psyml-settings',
            'query_var'          => true,
            'rewrite'            => array( 'slug' => 'psyml-subdimension' ),
            'capability_type'    => 'post',
            'has_archive'        => true,
            'hierarchical'       => false,
            'menu_icon'          => 'dashicons-admin-post',
            'menu_position'      => 5,
            'show_in_rest'       => false,
          #  'rest_base'          => 'psyML',
          #  'rest_controller_class' => 'WP_REST_Posts_Controller',
            'supports'           => array( 'title', 'editor', 'post-thumbnails', 'page-attributes'),
            'taxonomies'         => array( 'hexaco')       
        );
    
        \register_post_type( 'psyml-subdimension', $args );

    }
}